WITH OWNERSHIP AS (
    SELECT
        A.ID,
        A.NAME AS ACCT_NAME,
        U.EMAIL AS CURRENT_OWNER_EMAIL
    FROM
        sfdcAccount AS A
        LEFT JOIN sfdcUser U ON A.OWNERID = U.ID
)
SELECT
    A.*,
    OWNERSHIP.CURRENT_OWNER_EMAIL
FROM
    tblAlign_Act A
    LEFT JOIN OWNERSHIP ON A.ACT_ID = OWNERSHIP.ID
WHERE
    END_DT = '2099-12-31'
    AND OWNER_EMAIL <> CURRENT_OWNER_EMAIL