SELECT
    C.CASENUMBER,
    ACCOUNTID,
    OPPORTUNITY__C,
    OPPORTUNITY_OWNER__C,
    format(PRIOR_AUTH_SUBMISSION_DATE__C, 'yyyy_MM') AS SUBMIT_YYYY_MM,
    RECORDTYPEID,
    STATUS,
    P.SPIF_PO_YYYYMM,
    P.CASENUMBER AS SPIF_PO_CASE,
    P.EMAIL AS SPIF_PO_EMAIL
FROM
    sfdcCase C
    LEFT JOIN tblCPAS_PO P ON C.OPPORTUNITY__C = P.OPP_ID
WHERE
    C.CASENUMBER IN (5091, 4916, 5152, 5151)