WITH LOA AS (
    SELECT
        *,
        DATEADD(MONTH, 3, LOA_END) AS POLICY_END
    FROM
        tblActSplits
    WHERE
        [LOA_Coverage?] = 1
)
SELECT
    SALES_CREDIT_REP_EMAIL,
    NAME_REP,
    -- REGION_ID,
    CLOSEDATE,
    CLOSE_YYYYMM,
    IMPLANTED_DT,
    IMPLANTED_YYYYMM,
    ACCOUNT_INDICATION__C,
    TM.ACT_ID,
    OPP_NAME,
    OPP_ID,
    SALES_COMMISSIONABLE,
    IMPLANT_UNITS,
    REVENUE_UNITS,
    LOA.REP_EMAIL AS POST_LOA_CREDIT_EMAIL,
    SALES_COMMISSIONABLE *.5 AS POST_LOA_SALES_COMMISSIONABLE
FROM
    qry_COMP_TM_DETAIL TM
    INNER JOIN LOA ON LOA.ACT_ID = TM.ACT_ID
    AND CLOSEDATE BETWEEN LOA_END
    AND POLICY_END
WHERE
    SALES_CREDIT_REP_EMAIL <> LOA.REP_EMAIL