SELECT
    CLOSE_YYYYMM,
    ATM_EMAIL,
    ATM_NAME,
    REGION,
    ISNULL(SUM(IMPLANT_UNITS), 0) AS IMPLANT_UNITS,
    ISNULL(SUM(REVENUE_UNITS), 0) AS REVENUE_UNITS,
    ISNULL(SUM(SALES_COMMISSIONABLE), 0) AS SALES_COMMISSIONABLE,
    ISNULL(SUM(PAYOUT), 0) AS PAYOUT
FROM
    qry_COMP_ATM_DETAIL
WHERE
    CLOSE_YYYYMM = FORMAT(DATEADD(MONTH, -1, GETDATE()), 'yyyy_MM')
GROUP BY
    CLOSE_YYYYMM,
    ATM_EMAIL,
    ATM_NAME,
    REGION