DECLARE @FIRST_IMPLANT_DT AS NVARCHAR(7) = '2024-07'
SELECT
    [NAME],
    [ACU_DATE__C],
    [DATE_OF_FIRST_COMMERCIAL_IMPLANT__C],
    FORMAT(
        cast(DATE_OF_FIRST_COMMERCIAL_IMPLANT__C AS date),
        'yyyy-MM'
    ) AS MONTH_OF_FIRST_COMMERCIAL_IMPLANT,
    [DATE_OF_LAST_COMMERCIAL_IMPLANT__C],
    [DHC_IDN_NAME__C]
FROM
    [dbo].[qryCust]
WHERE
    DATE_OF_FIRST_COMMERCIAL_IMPLANT__C IS NOT NULL
    AND DHC_IDN_NAME__C IS NOT NULL
    AND FORMAT(
        cast(DATE_OF_FIRST_COMMERCIAL_IMPLANT__C AS date),
        'yyyy-MM'
    ) = @FIRST_IMPLANT_DT -- AND LOWER(DHC_IDN_NAME__C) LIKE '%cleveland%'
ORDER BY
    CAST(DATE_OF_FIRST_COMMERCIAL_IMPLANT__C AS date) DESC