-- CREATE VIEW qryCust AS
SELECT
    W.NAME AS ACT_TYPE,
    REPLACE(dbo.ConvertToTitleCase(A.NAME), '?', '') AS NAME,
    A.ACU_DATE__C,
    A.ACU_INITIATION_DATE__C,
    A.STATUS_COLOR__C,
    A.STATUS__C,
    A.DATE_OF_FIRST_COMMERCIAL_IMPLANT__C,
    q.YYYYMM [MNTH_FIRST_IMPLANT],
    q2.YYYYMM [YYYYMM_LAST_IMPLANT],
    q.YYYYQQ [QTR_FIRST_IMPLANT],
    A.DATE_OF_LASTCOMMERCIAL_IMPLANT__C AS DATE_OF_LAST_COMMERCIAL_IMPLANT__C,
    CASE
        WHEN a.DATE_OF_LASTCOMMERCIAL_IMPLANT__C = '1899-12-30 00:00:00' THEN NULL
        ELSE DATEDIFF(
            MONTH,
            A.DATE_OF_LASTCOMMERCIAL_IMPLANT__C,
            GETDATE()
        )
    END AS MNTH_LAST_IMPLANT,
    A.CATEGORY__C,
    A.CHAMPION_IDENTIFICATION__C,
    A.CHAMPION_S_DEVELOPED__C,
    A.CMS_ID__C,
    A.COMMERCIAL_ACTIVATION_PERCENT_COMPLETE__C,
    A.ID,
    A.DHC_ACCOUNT_ID__C,
    A.DHC_IDN_NAME__C,
    A.DHC_IDN_NUMBER__C,
    A.PRIMARY_GPO__C,
    A.PRIMARY_GPO_ID__C,
    D.[CSA ID],
    D.CSA_NAME,
    F.cbsa_name,
    F.cbsa,
    A.IN_DEVELOPMENT_PERCENT_COMPLETE__C,
    A.INDUSTRY,
    A.ISDELETED,
    A.ISPARTNER,
    CASE
        WHEN A.STAGE_NEW__C = 'Activated for commercial use (ACU)' THEN 1
        WHEN YEAR(DATE_OF_FIRST_COMMERCIAL_IMPLANT__C) > '2019' THEN 1
        ELSE 0
    END AS ISACU,
    A.MARKET__C,
    A.MONTHS_TO_ACU__C,
    A.MONTHS_TO_FIRST_COMMERCIAL_IMPLANT__C,
    A.OWNERID,
    B.NAME AS OWNER_NAME,
    B.EMAIL AS OWNER_EMAIL,
    E.REP_EMAIL,
    B.LASTNAME AS OWNER_LNAME,
    B.TITLE_REV AS OWNER_TITLE,
    B.US_REGION__C,
    ISNULL(E.REGION, E2.REGION) AS REGION,
    ISNULL(E.REGION_ID, E2.TERRITORY_ID) AS REGION_ID,
    A.REFERRAL_NETWORK_ESTABLISHED__C,
    A.REGION_USA_ONLY__C,
    A.SHIPPINGCITY,
    A.SHIPPINGCOUNTRY,
    A.SHIPPINGCOUNTRYCODE,
    LEFT(
        CASE
            WHEN LEN(RTRIM(LTRIM(A.SHIPPINGPOSTALCODE))) >= 5 THEN RTRIM(LTRIM(A.SHIPPINGPOSTALCODE))
            ELSE RIGHT('00000' + RTRIM(LTRIM(A.SHIPPINGPOSTALCODE)), 5)
        END,
        5
    ) AS SHIPPINGPOSTALCODE,
    A.SHIPPINGSTATE,
    A.SHIPPINGSTATECODE,
    A.SHIPPINGSTREET,
    A.STAGE_NEW__C,
    A.SURGEON_S_TRAINED__C,
    A.TOTAL_RECOGNIZED_IMPLANT__C,
    A.US_REGION_USER_RECORD__C,
    A.VALUE_ANALYSIS_INITIATED__C,
    CASE
        WHEN TOTAL_RECOGNIZED_IMPLANT__C > 0 THEN AIC__C
        ELSE 0
    END AS isAIC,
    A.CONTRACTING_DISCUSSIONS_INITIATED__C,
    A.CONTRACTING__C,
    A.PRICE_BOOK__C,
    K.Blueprint_Type__c,
    CASE
        WHEN A.ID IN (
            SELECT
                DISTINCT ACCOUNTID
            FROM
                sfdcOpps
        ) THEN 1
        ELSE 0
    END AS [HasOpps?],
    A.Account_Tier__c
FROM
    dbo.sfdcAccount AS A
    LEFT OUTER JOIN dbo.qryUsers AS B ON A.OWNERID = B.ID
    LEFT OUTER JOIN dbo.tblCSA AS D ON LEFT(
        CASE
            WHEN LEN(RTRIM(LTRIM(A.SHIPPINGPOSTALCODE))) >= 5 THEN RTRIM(LTRIM(A.SHIPPINGPOSTALCODE))
            ELSE RIGHT('00000' + RTRIM(LTRIM(A.SHIPPINGPOSTALCODE)), 5)
        END,
        5
    ) = D.ZIP
    LEFT OUTER JOIN dbo.qryRoster AS E ON B.EMAIL = E.REP_EMAIL
    AND E.[isLATEST?] = 1
    LEFT OUTER JOIN dbo.qryRoster_RM AS E2 ON B.EMAIL = E2.EMP_EMAIL
    LEFT OUTER JOIN dbo.qryCBSA AS F ON LEFT(
        CASE
            WHEN LEN(RTRIM(LTRIM(A.SHIPPINGPOSTALCODE))) >= 5 THEN RTRIM(LTRIM(A.SHIPPINGPOSTALCODE))
            ELSE RIGHT('00000' + RTRIM(LTRIM(A.SHIPPINGPOSTALCODE)), 5)
        END,
        5
    ) = F.zip
    LEFT OUTER JOIN dbo.sfdcRecordType AS W ON A.RECORDTYPEID = W.ID
    LEFT JOIN ODS.sfdcBlueprint K ON a.ID = k.Account__c
    AND k.IsDeleted = 0
    AND k.Status__c = 'Active'
    LEFT JOIN qryCalendar Q ON a.DATE_OF_FIRST_COMMERCIAL_IMPLANT__C = q.DT
    LEFT JOIN qryCalendar Q2 ON a.DATE_OF_LASTCOMMERCIAL_IMPLANT__C = q2.DT
WHERE
    (A.NAME NOT LIKE '%test%')
    AND W.NAME = 'Customer'