-- CREATE VIEW qryRates_TM AS
SELECT
    TERRITORY_ID,
    EID,
    TIER,
    CAST([PLAN] AS MONEY) AS PLAN_FY,
    CAST(THRESHOLD AS MONEY) AS THRESHOLD_FY,
    CAST(THRESHOLD * 0.21 AS MONEY) AS Q1_BL,
    CAST([PLAN] * 0.21 AS MONEY) AS Q1_Q,
    CAST(THRESHOLD * 0.25 AS MONEY) AS Q2_BL,
    CAST([PLAN] * 0.25 AS MONEY) AS Q2_Q,
    CAST(THRESHOLD * 0.26 AS MONEY) AS Q3_BL,
    CAST([PLAN] * 0.26 AS MONEY) AS Q3_Q,
    CAST(THRESHOLD * 0.28 AS MONEY) AS Q4_BL,
    CAST([PLAN] * 0.28 AS MONEY) AS Q4_Q
FROM
    tblRates_TM