SELECT
    A.ACCOUNT_INDICATION__C,
    A.ACCOUNT_OWNER_ALIAS__C,
    A.ISACU,
    A.OPP_ID,
    A.ACT_ID,
    CASE
        WHEN B.ACT_ID IS NOT NULL THEN 1
        ELSE 0
    END AS SPLIT_FLAG,
    A.SHIPPINGSTATECODE,
    A.SHIPPINGCITY,
    A.OPPORTUNITY_REGION__C,
    A.OPP_COUNTRY,
    A.SALES_CREDIT_REP,
    ISNULL(A.SALES_CREDIT_REP_EMAIL, A.OPP_OWNER_EMAIL) AS SALES_CREDIT_REP_EMAIL,
    A.OPP_OWNER_NAME,
    A.OPP_OWNER_LNAME,
    A.OPP_OWNER_ALIAS,
    A.OPP_OWNER_EMAIL,
    A.OPP_OWNER_TITLE,
    A.OPP_OWNER_ISACTIVE,
    A.OPP_OWNER_REGION,
    A.SALES_CREDIT_TERR_NM,
    A.REG_ID,
    A.ACT_OWNER_NAME,
    A.ACT_OWNER_LNAME,
    A.ACT_OWNER_ALIAS,
    A.ACT_OWNER_TITLE,
    A.ACT_OWNER_EMAIL,
    A.ACT_OWNER_ISACTIVE,
    A.ACT_OWNER_REGION,
    A.PHYSICIAN,
    A.PHYSICIAN_SPECIALTY,
    A.RECORD_TYPE,
    A.IMPLANT_COMPLETE_NAME,
    A.IMPLANT_COMPLETE_REGION,
    A.TOTALOPPORTUNITYQUANTITY,
    CASE
        WHEN REASON_FOR_IMPLANT__C = 'De novo' THEN TOTALOPPORTUNITYQUANTITY
        ELSE 0
    END AS TOTALOPPORTUNITYQUANTITY_NEW,
    CASE
        WHEN REASON_FOR_IMPLANT__C = 'Replacement' THEN TOTALOPPORTUNITYQUANTITY
        ELSE 0
    END AS TOTALOPPORTUNITYQUANTITY_REPLC,
    A.IMPLANT_UNITS,
    A.REVENUE_UNITS,
    A.CREATEDDATE,
    A.CREATED_YYYYMM,
    A.CREATED_YYYY,
    A.CLOSEDATE,
    A.CLOSE_YYYYMM,
    A.CLOSE_YYYYQQ,
    A.CLOSE_YYYY,
    A.SALES,
    CASE
        WHEN REASON_FOR_IMPLANT__C = 'De novo' THEN SALES
        ELSE 0
    END AS SALES_NEW,
    CASE
        WHEN REASON_FOR_IMPLANT__C = 'Replacement' THEN SALES
        ELSE 0
    END AS SALES_REPLC,
    A.ASP,
    A.INDICATION_FOR_USE__C,
    A.ISCLOSED,
    A.NAME,
    A.PATIENT_IPG_SERIAL_NUMBER__C,
    A.PO_RECEIVED__C,
    A.PO_REIMBURSEMENT_STATUS__C,
    A.REASON_FOR_IMPLANT__C,
    A.REPLACEMENT_TYPE__C,
    A.STAGENAME,
    A.INTERESTED_DT,
    A.IMPLANTED_DT,
    A.IMPLANTED_YYYYMM,
    A.IMPLANTED_YYYY,
    A.IMPLANTED_YYYYQQ,
    A.ISIMPL,
    A.REGION,
    A.SALES_CREDIT_RM,
    A.isAIC,
    A.PHYSICIAN_ID,
    A.REFERRAL_TYPE,
    A.[isMDRTarget?],
    A.REFERRAL_COUNT_CLOSED AS [REFERRAL COUNT],
    A.OPPORTUNITY_SOURCE__C,
    A.CREATED_R12,
    A.CREATED_R6,
    A.CREATED_R3,
    A.AM_FOR_CREDIT,
    A.AM_FOR_CREDIT_EMAIL,
    A.OPP_STATUS
FROM
    dbo.qryOpps AS A
    LEFT OUTER JOIN (
        SELECT
            DISTINCT ACT_ID
        FROM
            dbo.tblActSplits
    ) AS B ON A.ACT_ID = B.ACT_ID
WHERE
    (A.STAGENAME = 'Revenue Recognized')
    AND (A.REASON_FOR_IMPLANT__C <> 'De novo - BATwire')
    OR (
        A.STAGENAME IN ('Implant Completed', 'Revenue Recognized')
    )
    AND (A.REASON_FOR_IMPLANT__C = 'De novo - BATwire')